//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieDemo.GetMovieService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieOffer
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string ToMail { get; set; }
        public int MovieId { get; set; }
        public Nullable<int> MoviesId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Movie Movie { get; set; }
        public virtual User User { get; set; }
    }
}
